import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home({ data }) {
  console.log("data");
  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        <li>
          <Link href="/">Home</Link>
        </li>
        <li>
          <Link href="/about">About Us</Link>
        </li>
        <li>
          <Link href="/users">Users</Link>
        </li>
      </ul>
      <div>
        <h1>Halaman Home</h1>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const req = await getData("api/v1/events");
  const res = req.data;

  return {
    props: { data: res },
  };
}
